### ISSUE TITLE
'extractSerpent2GCs.py' should allow more flexible input data naming convention

### ISSUE THREAD

**Issue by robfairh** [arfc/moltres#103]
The tutorial:
https://github.com/arfc/moltres/tree/devel/tutorial/step01_groupConstants

defines serpent input files for the materials 'fuel' and 'moder' with the same names. Then, serpent produces the XS in the .coe files with the same names ('fuel.coe' and 'moder.coe'). In the case I have only one serpent input file, the .coe file won't have the same name as the materials, casing 'extractSerpent2GCs.py' to fail.

This issue can be closed when 'extractSerpent2GCs.py' allows a more flexible naming convention.

**Comment by gridley** [comment]
Are you simultaneously perturbing temperatures on each material, or one at a time? It was written like this because if you do all the branching in one file, Serpent will cover the whole case matrix of mixtures of each temperature you're covering in each material. So, I split the simulations into one serpent input per material, where each input file covers the temperature perturbations for that material.

If you're trying to cover the full mixture of moderator/fuel temperatures, I recommend writing a new script to parse the data since this was not built with that end in mind.

**Comment by robfairh** [comment]
Okay, I see. I was trying to get the moltres input data for this serpent file:
https://github.com/arfc/msr-neutronics/blob/master/MSFR/serpent/MSFR_base
where all the branching is defined in that file. What are the XS in the .coe then? Is that the homogenized data? Or is it the XS for the fuel (branch fuel0) when all the materials are in thermal equilibirum? This is clearly a different approach to the one in the tutorial. Does it mean that is incorrect or just inefficient? 
@smpark7 how do you get the XS for moltres for that serpent file?

**Comment by smpark7** [comment]
The script allows for temperature perturbations on one material per Serpent input file. For that Serpent input file in the link, I "cheated" by defining uniform temperature across the whole reactor for each branch, and copying the single .coe file into numerous copies for each material. That's why it looks inefficient. I did this because it was easier to put everything into one Serpent run and it takes less than ~15min to run the Serpent input on Blue Waters

**Comment by robfairh** [comment]
That's okay. I think for now we can leave it like this but I believe that the tutorial should mention this. Otherwise, other users (like me) will have to struggle for some minutes until realizing what's going on.
So the issue can be closed when a few lines in the tutorial mention this.

**Comment by robfairh** [comment]
This issue will be closed and will remain as a reference for people who struggle to follow the tutorial to convert the XS from serpent to moltres format.
