### ISSUE TITLE
Add openmc interface to moltres_xs.py

### ISSUE THREAD

**Issue by gwenchee** [arfc/moltres#126]
This issue can be closed when the capability to extract homogenized group constants from OpenMC to Moltres is added. 
This should be added to https://github.com/arfc/moltres/blob/devel/python/moltres_xs.py

**Comment by gwenchee** [comment]
<img width="595" alt="Screen Shot 2020-10-16 at 10 08 19 PM" src="https://user-images.githubusercontent.com/29397884/96268828-1c8b5280-0ffc-11eb-8bb1-cc72fbc93b97.png">
This is the table I made outlining the openmc constants that correspond to the moltres ones

**Comment by gwenchee** [comment]
@yardasol Hey Olek, what's the status of this?

**Comment by yardasol** [comment]
@gwenchee It's been a while since I worked on this. Looking back at our convos in slack and my own personal meeting notes, I was having issues with the conda package of openmc, so I was going to build from source. I think that project became its own little rabbit hole, but I did make a script out of it so that I can now install openmc from source automatically (I think). I was also going to begin writing a script based on some resources you gave me.

I'll spend some time on this tomorrow so I can paint a picture of what I've already figured out and what isn't working and move forward from there.

**Comment by katyhuff** [comment]
Thanks. I assume you're following the instructions here: https://docs.openmc.org/en/stable/usersguide/install.html#prerequisites.  If you have trouble of course openmc has an issue tracker, [where a few common issues with installation have been discussed with new users](https://github.com/openmc-dev/openmc/issues?q=is%3Aissue+install).

**Comment by yardasol** [comment]
Hi @gwenchee, so sorry for the lack of updates. Long story short I've been busy with other projects. I didn't realize that this was that urgent for you, if it was I would have made it more of a priority! Very sorry about this.

**Comment by gwenchee** [comment]
Ya no worries! Thanks for letting me know

**Comment by gwenchee** [comment]
closed with #174
