### ISSUE TITLE
Create templates for issues and pull requests

### ISSUE THREAD

**Issue by yardasol** [arfc/moltres#130]
EDIT 1: The first comment below strongly discourages an entire new document be created for contributing and suggests using GitHub templates instead along with editing he CONTRIBUTING.md document. I agree this is a much more efficient approach. The issue has been updated to reflect this.

Moltres development could be improved by adding templates for issues and pull requests. The existence of these templates can be noted in the CONTRIBUTING.md document.

This issue can be closed when templates for issues and pull requests exist, and the existence of these templates is specified in the CONTRIBUTING.md document.

Original issue preserved below
-----------------------------
Original Title: Create a Contributing Guide

Moltres does not have a Contributing Guide. A Contributing Guide defines the appropriate procedure for making contributions to a project. A contributing guide is important for open source projects like Moltres to ensure that code issues are dealt with appropriately and efficiently.

The Contributing Guide should specify

 - steps for submitting a bug report/feature request/other misc. project thingy and the expected structure of such a report/request/thingy
 - steps for reviewing a bug report/feature request/other misc. project thingy and the expected structure of such a review of said report/request/thingy

Many of these items already exist in the [current CONTRIBUTING.md document](https://github.com/arfc/moltres/blob/devel/CONTRIBUTING.md).

This list is not comprehensive and should be updated as necessary. The Contributing Guide should use clear, concise, and easy to read language. A good place to start for inspiration might be the [ARFC Guides](http://arfc.github.io/manual/guides/) or the [OpenMC contributing guide](https://docs.openmc.org/en/latest/devguide/contributing.html)

This issue can be closed once a Contributing guide that addresses the above items exists.

**Comment by katyhuff** [comment]
- Moltres has a contributors guide. It's CONTRIBUTING.md, which you've noted. A new "contributing guide" should not be created. If things are missing from contributing.md, then perhaps they should be added to contributing.md. A new document should *not* be created because it will create a second place to maintain in parallel.
- There is no need in any git workflow for folks to "bug report/feature request/other misc. project thingy". There is already a whole section in ONTRIBUTING.md on reviewing pull requests. https://github.com/arfc/moltres/blob/devel/CONTRIBUTING.md#reviewing-a-pull-request

If you'd like to add a section to contributing.md about how to create an issue, then that would be a fine thing. If you'd like to add an issue_template or pull_request_template, then that would be fine too. 

I strongly discourage a second document.

**Comment by yardasol** [comment]
I see your point and I agree. The issue has been updated.

**Comment by katyhuff** [comment]
Thanks!!
