### ISSUE TITLE
Compilation issue on MacOS with clang

### ISSUE THREAD

**Issue by nglaser3** [arfc/moltres#269]
## Expected behavior
Expect Moltres to compile completely with clang on MacOS with M2 chip. 

## Describe the bug
When compiling moltres, clang does not recognize certain modules as 'template', for example:

```
error: 'adCoupledValue' following the 'template' keyword does not refer to a template
    _mu_tilde(this->template adCoupledValue("mu_tilde")),
```
The full list of errors outputted from make is below. Because of these errors Moltres is not compiling.

## To Reproduce
1. clone Moltres repository
2. git checkout devel
3. git submodule init / git submodule update
4. cd moltres
5. run make -j8 on MacOS M2

## Screenshots/output
Compilation of moltres with clang:
[compilation.txt](https://github.com/arfc/moltres/files/15474768/compilation.txt)
generated errors:
[errors.txt](https://github.com/arfc/moltres/files/15474761/errors.txt)

## System Specifications:
 - Version: MacOS Sonoma 14.5
 - Platform: M2 Chip

## How can this issue be closed?
Compilation of Moltres on MacOS with M2 Chip

**Comment by smpark7** [comment]
This bug appears to be due to clang and gcc having different rules regarding C++. It is possible that our code in `SATauMaterial` is running afoul of C++ standards for calling functions from the base class in a derived template class. I will make a quick attempt at fixing this, failing which I will ask the MOOSE team for help.

**Comment by smpark7** [comment]
This is the same issue described in discussion #259
