### ISSUE TITLE
Error getting pre-concs values from previous run for restart

### ISSUE THREAD

**Issue by joonhon** [arfc/moltres#80]
This error appears in the LOSCA example problem in /MOLTRES/problems/LOSCA as well as other input files that attempted to retrieve pre-concs values from previous simulations (.e files).

To replicate the error:
1) cd to /MOLTRES/problems/LOSCA
2) Mesh the geo file. (Follow the same step as described in https://github.com/arfc/moltres/tree/devel/problems/LOSCA)
3) Run the input file "auto_diff_rho.i". (also described above)
4) cd to /MOLTRES/problems/LOSCA/HXFailure
5) Run the input file "auto_diff_rho.i". (also described above). You will encounter the unrelated errors pertaining to missing parameters "group_number" and "block" within the "delayed_group1" kernel.
6) To proceed, open the input file and add "group_number = 1" and "block = 'fuel'" into the "delayed_group1" kernel.
7) Run the input file again. You will receive the following error message: "Error getting elemental values.
[0] ../src/mesh/exodusII_io_helper.C, line 1055, compiled Sep 25 2018 at 14:47:44".
8) (7) is the main error of this topic. This error message also appears when one tries to use SolutionUserObject to obtain the pre-concs values from a previous simulation (.e file).
Note: Sep 25 2018 was probably the day when I built MOLTRES on that computer.

**Comment by katyhuff** [comment]
Can you update moose and moltres, and rebuild, then see if you still get this error? New changes in moltres have been made to keep moltres up to date with new versions of moose... It's usually best to use the most updated version.

**Comment by joonhon** [comment]
Hi all, just rebuilt moose and moltres to the latest versions. Re-ran the above LOSCA example and the error persisted: 
"Error getting elemental values.
[0] ../src/mesh/exodusII_io_helper.C, line 1059, compiled Feb 18 2019 at 20:14:09
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0"

Examining the exodusII_io_helper.C file, line 1059 is:
`      EX_CHECK_ERR(ex_err, "Error getting elemental values.");`

      std::vector<Real> block_elem_var_values(num_elem);
      ex_err = exII::ex_get_elem_var(ex_id,
                                     time_step,
                                     var_index+1,
                                     block_ids[i],
                                     num_elem_this_blk,
                                     block_elem_var_values.data());
      EX_CHECK_ERR(ex_err, "Error getting elemental values.");

**Comment by gridley** [comment]
Well, since this superficially looks deeper than Moltres. The first thing to do is check which branch of MOOSE you pulled from---it could be a bleeding-edge branch failing unit tests. To figure out if it is MOOSE, you could try to run something dead-simple: heat conduction. See this example.

https://github.com/idaholab/moose/blob/next/modules/heat_conduction/test/tests/verify_against_analytical/1D_transient.i

I propose that you take this simulation, and rather than go for 100 seconds, split the simulation into two input files: one for 50 seconds, printing its results to a file, then a second reading the results from the first to run it out to 100. Then you can compare that to the 0-100 run. If the second fails to load or they disagree, you should raise an issue to idaholab/moose. Unfortunately I do not have time to do that at the moment, so good luck! :smile:

**Comment by lindsayad** [comment]
A working path is [here](https://github.com/libMesh/libmesh/pull/2041)

**Comment by joonhon** [comment]
@lindsayad Thanks! I recompiled libmesh (and MOLTRES) with the modified exodusII_io_helper.C and there are no more problems with restarting using the previous run's pre-conc values!

**Comment by lindsayad** [comment]
That's great to hear!

**Comment by gridley** [comment]
Does this work now for sure @joonhon? If so the issue could be closed.

**Comment by joonhon** [comment]
Hi Gavin, thanks for the reminder. I believe the issue has been resolved. I'll close the issue, Thanks!
